apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkite-agent
spec:
  replicas: 1
  template:
    metadata:
        labels:
            app: buildkite-agent
    spec:
        containers:
            - name: buildkite-agent
              image: buildkite/agent
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
                - name: BUILDKITE_AGENT_TOKEN
                  valueFrom:
                    secretKeyRef:
                        name: buildkite-agent
                        key: token
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: ssh-keys
                  mountPath: /root/.ssh/id_rsa
                  subPath: id_rsa
                - name: ssh-keys
                  mountPath: /root/.ssh/id_rsa.pub
                  subPath: id_rsa.pub
        volumes:
            - name: docker-socket
              hostPath: {path: /var/run/docker.sock}
            - name: ssh-keys
              secret:
                secretName: buildkite-agent-ssh
                defaultMode: 0400
 
                 

            